title: Gmail Utils
description: A repository of various utilities which are useful for Gmail.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
